import { store } from './services/store.js';
import { resumenVerificacionesDocente } from './services/verificador-remoto.js';
const $ = s => document.querySelector(s); let datos = null;
const money = n => typeof n === 'number' ? `US$ ${n.toLocaleString('es-CL', { maximumFractionDigits: 0 })}` : '—';
const pct = n => typeof n === 'number' ? `${(n * 100).toLocaleString('es-CL', { maximumFractionDigits: 2 })}%` : '—';
function csv(v) { return `"${String(v ?? '').replaceAll('"', '""')}"`; }
async function cargar() { try { datos = await resumenVerificacionesDocente(); const filas = Object.entries(datos.equipos); $('#resumen').innerHTML = filas.length ? `<table class="tabla"><thead><tr><th>Equipo</th><th>Pruebas</th><th>Primera válida</th><th class="num">Mejor costo válido</th><th class="num">Mejor brecha</th></tr></thead><tbody>${filas.map(([e, r]) => `<tr><td>${e}</td><td>${r.pruebas}</td><td>${r.primera_valida ? new Date(r.primera_valida).toLocaleString('es-CL') : '—'}</td><td class="num">${money(r.mejor_costo_valido)}</td><td class="num">${pct(r.mejor_brecha_referencia)}</td></tr>`).join('')}</tbody></table>` : '<p class="muted">Aún no hay verificaciones registradas.</p>'; $('#errores').innerHTML = datos.errores_frecuentes?.length ? `<table class="tabla"><thead><tr><th>Error</th><th class="num">Veces</th></tr></thead><tbody>${datos.errores_frecuentes.map(([e, n]) => `<tr><td>${e}</td><td class="num">${n}</td></tr>`).join('')}</tbody></table>` : '<p class="muted">Aún no hay errores registrados.</p>'; } catch (e) { $('#error').textContent = e.message || 'No fue posible cargar el panel.'; } }
$('#entrar').addEventListener('click', async () => { $('#error').textContent = ''; try { await store.entrarDocente(); $('#ingreso').hidden = true; $('#panel').hidden = false; await cargar(); } catch (e) { $('#error').textContent = e.message || 'No fue posible ingresar.'; } });
$('#salir').addEventListener('click', async () => { await store.salirDocente(); $('#panel').hidden = true; $('#ingreso').hidden = false; });
$('#csv').addEventListener('click', () => { if (!datos) return; const filas = [['Equipo','Pruebas','Primera válida','Mejor costo válido','Brecha Parte B'], ...Object.entries(datos.equipos).map(([e,r]) => [e,r.pruebas,r.primera_valida,r.mejor_costo_valido,r.mejor_brecha_referencia])]; const u = URL.createObjectURL(new Blob(['\uFEFF' + filas.map(r => r.map(csv).join(';')).join('\n')], {type:'text/csv;charset=utf-8'})); const a=document.createElement('a'); a.href=u; a.download='registro-verificador.csv'; a.click(); URL.revokeObjectURL(u); });
